<a href="https://colab.research.google.com/github/ghowtham12/task-8/blob/main/NLP_laguage_translation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv('/content/English.csv')
df

                                  English words/sentences
0                                                     Hi.
1                                                    Run!
2                                                    Run!
3                                                    Who?
4                                                    Wow!
...                                                   ...
175616  Top-down economics never works, said Obama. "T...
175617  A carbon footprint is the amount of carbon dio...
175618  Death is something that we're often discourage...
175619  Since there are usually multiple websites on a...
175620  If someone who doesn't know your background sa...

[175621 rows x 1 columns]

In [3]:
df1 = df.head(500)

In [12]:
from deep_translator import GoogleTranslator
german =[]
for i in df1['English words/sentences']:
      a = GoogleTranslator(source='auto', target='de').translate(i)
      german.append(''.join(a))

In [13]:
ge =pd.Series(german)
ger=pd.DataFrame(ge, columns=["german words"])
ger.head(10)

  german words
0          Hi.
1      Laufen!
2      Laufen!
3         Wer?
4         Wow!
5       Feuer!
6       Hilfe!
7    Springen.
8        Halt!
9        Halt!

In [14]:
spanish =[]
for j in df1['English words/sentences']:
  b = GoogleTranslator(source='auto', target='spanish').translate(j)
  spanish.append(''.join(b))

In [15]:
sp =pd.Series(spanish)
spa=pd.DataFrame(sp, columns=["spanish words"])
spa.head()

  spanish words
0         Hola.
1      Â¡Correr!
2      Â¡Correr!
3       Â¿QuiÃ©n?
4        Â¡Guau!

In [16]:
french =[]
for k in df1['English words/sentences']:
  c = GoogleTranslator(source='auto', target='french').translate(k)
  french.append(''.join(c))

In [17]:
fe =pd.Series(french)
fer=pd.DataFrame(fe, columns=["french words"])
fer.head()

  french words
0       Salut.
1      Courir!
2      Courir!
3         Qui?
4        Ouah!

In [18]:
different_lan = pd.concat([df1,ger,spa,fer],axis=1)
different_lan.head()

  English words/sentences german words spanish words french words
0                     Hi.          Hi.         Hola.       Salut.
1                    Run!      Laufen!      Â¡Correr!      Courir!
2                    Run!      Laufen!      Â¡Correr!      Courir!
3                    Who?         Wer?       Â¿QuiÃ©n?         Qui?
4                    Wow!         Wow!        Â¡Guau!        Ouah!